name: smtp
owner: buggregator
description: "SMTP server plugin for debugging and profiling email traffic in development environments"
category: network
dependencies:
  - logger
  - server
docsUrl: https://github.com/buggregator/smtp-server
author:
  name: RoadRunner Team
  url: https://github.com/buggregator
license: MIT
keywords:
  - smtp
  - email
  - debugging
  - profiling
  - buggregator
