name: smtp
owner: roadrunner-plugins
description: "SMTP server plugin for debugging and profiling email traffic in development environments"
category: network
dependencies:
  - logger
  - server
docsUrl: https://github.com/roadrunner-plugins/smtp-server
author:
  name: RoadRunner Team
  url: https://github.com/roadrunner-plugins
license: MIT
keywords:
  - smtp
  - email
  - debugging
  - profiling
  - buggregator
